=== bakos8/M95ETT_XMLGyak/XMLTaskM95ETT/XMLSchemaM95ETT.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="Ablakgyar">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Uvegek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Uveg" type="UvegTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Beepitesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Beepites" type="BeepitesTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Rendelesek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rendeles" type="RendelesTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Profilok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Profil" type="ProfilTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Parkanyok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Parkany" type="ParkanyTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Anyagok">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Anyag" type="AnyagTipus" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

        <xs:unique name="rendelesszam_fk">
            <xs:selector xpath="Rendelesek/Rendeles" />
            <xs:field xpath="@rendelesszam" />
        </xs:unique>

        <xs:unique name="profilID_fk">
            <xs:selector xpath="Profilok/Profil" />
            <xs:field xpath="@profilID" />
        </xs:unique>

        <xs:unique name="parkanyID_fk">
            <xs:selector xpath="Parkanyok/Parkany" />
            <xs:field xpath="@parkanyID" />
        </xs:unique>

        <xs:keyref name="rendelesszam_fk-Uveg" refer="rendelesszam_fk">
            <xs:selector xpath="Uvegek/Uveg/rendelesszam_fk" />
            <xs:field xpath="." />
        </xs:keyref>

        <xs:keyref name="rendelesszam_fk-Beepites" refer="rendelesszam_fk">
            <xs:selector xpath="Beepitesek/Beepites/rendelesszam_fk" />
            <xs:field xpath="." />
        </xs:keyref>

        <xs:keyref name="rendelesszam_fk-Profil" refer="rendelesszam_fk">
            <xs:selector xpath="Profilok/Profil/rendelesszam_fk" />
            <xs:field xpath="." />
        </xs:keyref>

        <xs:keyref name="profilID_fk-Anyag" refer="profilID_fk">
            <xs:selector xpath="Anyagok/Anyag/profilID_fk" />
            <xs:field xpath="." />
        </xs:keyref>

        <xs:keyref name="parkanyID_fk-Anyag" refer="parkanyID_fk">
            <xs:selector xpath="Anyagok/Anyag/parkanyID_fk" />
            <xs:field xpath="." />
        </xs:keyref>

    </xs:element>

    <xs:complexType name="UvegTipus">
        <xs:sequence>
            <xs:element name="Retegszam" type="retegTipus" />
            <xs:element name="Hofolia" type="xs:string" />
            <xs:element name="rendelesszam_fk" type="xs:integer" />
        </xs:sequence>
        <xs:attribute name="uvegID" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="BeepitesTipus">
        <xs:sequence>
            <xs:element name="Datum" type="xs:string" />
            <xs:element name="Szakember" type="xs:string" />
            <xs:element name="rendelesszam_fk" type="xs:integer" />
        </xs:sequence>
        <xs:attribute name="beepID" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="RendelesTipus">
        <xs:sequence>
            <xs:element name="Rendeles_datum" type="xs:string" />
            <xs:element name="Megrendelo" type="megrendeloTipus" />
        </xs:sequence>
        <xs:attribute name="rendelesszam" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ProfilTipus">
        <xs:sequence>
            <xs:element name="Meret" type="xs:int" />
            <xs:element name="Anyag" type="anyagTipus" />
            <xs:element name="rendelesszam_fk" type="xs:int"></xs:element>
        </xs:sequence>
        <xs:attribute name="profilID" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ParkanyTipus">
        <xs:sequence>
            <xs:element name="Hossz" type="xs:int" />
            <xs:element name="Szelesseg" type="xs:int" />
        </xs:sequence>
        <xs:attribute name="parkanyID" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="AnyagTipus">
        <xs:sequence>
            <xs:element name="parkanyID_fk" type="xs:int" />
            <xs:element name="profilID_fk" type="xs:int" />
            <xs:element name="AzonosSzin" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="retegTipus">
        <xs:sequence>
            <xs:element name="Haromreteg" type="xs:int" />
            <xs:element name="Otreteg" type="xs:int" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="megrendeloTipus">
        <xs:sequence>
            <xs:element name="KapcsoaltfelvetelDatum" type="xs:string" />
            <xs:element name="Nev" type="xs:string" />
            <xs:element name="Telepules" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="anyagTipus">
        <xs:sequence>
            <xs:element name="Muanyag" type="xs:int" />
            <xs:element name="Fa" type="xs:int" />
            <xs:element name="Aluminium" type="xs:int" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== bakos8/M95ETT_XMLGyak/XMLTaskM95ETT/XMLM95ETT.xml
<?xml version="1.0" encoding="UTF-8"?>

<Ablakgyar xsi:noNamespaceSchemaLocation="./XMLSchemaM95ETT.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <!-- Üvegek példányosítása -->
    <Uvegek>
        <Uveg uvegID="145">
            <Retegszam>
                <Haromreteg>2</Haromreteg>
                <Otreteg>1</Otreteg>
            </Retegszam>
            <Hofolia>3</Hofolia>
            <rendelesszam_fk>182</rendelesszam_fk>
        </Uveg>

        <Uveg uvegID="146">
            <Retegszam>
                <Haromreteg>0</Haromreteg>
                <Otreteg>4</Otreteg>
            </Retegszam>
            <Hofolia>2</Hofolia>
            <rendelesszam_fk>185</rendelesszam_fk>
        </Uveg>

        <Uveg uvegID="147">
            <Retegszam>
                <Haromreteg>5</Haromreteg>
                <Otreteg>5</Otreteg>
            </Retegszam>
            <Hofolia>3</Hofolia>
            <rendelesszam_fk>186</rendelesszam_fk>
        </Uveg>
    </Uvegek>

    <!-- Beépítések példányosítása -->
    <Beepitesek>
        <Beepites beepID="034">
            <Datum>2022.06.15</Datum>
            <Szakember>2</Szakember>
            <rendelesszam_fk>182</rendelesszam_fk>
        </Beepites>

        <Beepites beepID="035">
            <Datum>2022.07.23</Datum>
            <Szakember>2</Szakember>
            <rendelesszam_fk>185</rendelesszam_fk>
        </Beepites>

        <Beepites beepID="036">
            <Datum>2022.08.10</Datum>
            <Szakember>4</Szakember>
            <rendelesszam_fk>186</rendelesszam_fk>
        </Beepites>
    </Beepitesek>

    <!-- Rendelések példányosítása -->
    <Rendelesek>
        <Rendeles rendelesszam="182">
            <Rendeles_datum>2022.05.11</Rendeles_datum>
            <Megrendelo>
                <KapcsoaltfelvetelDatum>2022.05.12</KapcsoaltfelvetelDatum>
                <Nev>Horváth Pálné</Nev>
                <Telepules>Maklár</Telepules>
            </Megrendelo>
        </Rendeles>

        <Rendeles rendelesszam="185">
            <Rendeles_datum>2022.06.20</Rendeles_datum>
            <Megrendelo>
                <KapcsoaltfelvetelDatum>2022.04.27</KapcsoaltfelvetelDatum>
                <Nev>Kiss Béla</Nev>
                <Telepules>Miskolc</Telepules>
            </Megrendelo>
        </Rendeles>

        <Rendeles rendelesszam="186">
            <Rendeles_datum>2022.07.26</Rendeles_datum>
            <Megrendelo>
                <KapcsoaltfelvetelDatum>2022.06.02</KapcsoaltfelvetelDatum>
                <Nev>Nagy Lajos</Nev>
                <Telepules>Kisköre</Telepules>
            </Megrendelo>
        </Rendeles>
    </Rendelesek>

    <!-- Profilok példányosítása -->
    <Profilok>
        <Profil profilID="003">
            <Meret>120</Meret>
            <Anyag>
                <Muanyag>3</Muanyag>
                <Fa>0</Fa>
                <Aluminium>0</Aluminium>
            </Anyag>
            <rendelesszam_fk>182</rendelesszam_fk>
        </Profil>

        <Profil profilID="008">
            <Meret>90</Meret>
            <Anyag>
                <Muanyag>2</Muanyag>
                <Fa>2</Fa>
                <Aluminium>0</Aluminium>
            </Anyag>
            <rendelesszam_fk>185</rendelesszam_fk>
        </Profil>

        <Profil profilID="012">
            <Meret>140</Meret>
            <Anyag>
                <Muanyag>5</Muanyag>
                <Fa>4</Fa>
                <Aluminium>1</Aluminium>
            </Anyag>
            <rendelesszam_fk>186</rendelesszam_fk>
        </Profil>
    </Profilok>

    <!-- Párkányok példányosítása -->
    <Parkanyok>
        <Parkany parkanyID="005">
            <Hossz>120</Hossz>
            <Szelesseg>35</Szelesseg>
        </Parkany>

        <Parkany parkanyID="013">
            <Hossz>90</Hossz>
            <Szelesseg>50</Szelesseg>
        </Parkany>

        <Parkany parkanyID="017">
            <Hossz>140</Hossz>
            <Szelesseg>40</Szelesseg>
        </Parkany>
    </Parkanyok>

    <!-- Anyagok példányosítása -->
    <Anyagok>
        <Anyag>
            <parkanyID_fk>005</parkanyID_fk>
            <profilID_fk>003</profilID_fk>
            <AzonosSzin>Igen</AzonosSzin>
        </Anyag>

        <Anyag>
            <parkanyID_fk>013</parkanyID_fk>
            <profilID_fk>008</profilID_fk>
            <AzonosSzin>Nem</AzonosSzin>
        </Anyag>

        <Anyag>
            <parkanyID_fk>017</parkanyID_fk>
            <profilID_fk>012</profilID_fk>
            <AzonosSzin>Igen</AzonosSzin>
        </Anyag>
    </Anyagok>
</Ablakgyar>
