=== bakos8/M95ETT_XMLGyak/M95ETT_0928/M95ETT_kurzusfelvetel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT BD_kurzusfelvetel (hallgato, kurzusok)>
    <!ATTLIST BD_kurzusfelvetel
        tanev CDATA #REQUIRED
        egyetem CDATA #FIXED "ME">

<!ELEMENT hallgato (hnev, szulev, szak+)>
    <!ATTLIST hallgato
        id CDATA #REQUIRED>

<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
    <!ATTLIST szak 
        evf CDATA #REQUIRED>

<!ELEMENT kurzusok (kurzus)*>

<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, oktato?)>
    <!ATTLIST kurzus
        id CDATA #REQUIRED
        jovahagyas CDATA "nem">

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>

=== bakos8/M95ETT_XMLGyak/M95ETT_0928/M95ETT_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BD_kurzusfelvetel SYSTEM "./M95ETT_kurzusfelvetel.dtd">

<BD_kurzusfelvetel tanev="2022_2023 I." egyetem="ME">
    
    <hallgato id="M95ETT">
        <hnev>Bakos Dominik</hnev>
        <szulev>1999-10-21</szulev>
        <szak evf="7">Programtervezo informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL332-B">
            <kurzusnev>Adatkezeles XML kornyezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>Kedd 12:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

        <kurzus id="GEIAL332-B" jovahagyas="igen">
            <kurzusnev>Vallalati informacios rendszerek fejlesztese</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf. 103</hely>
            <idopont>Szerda 16:00-17:30</idopont>
            <oktato>Dr. Sasvári Péter László</oktato>
        </kurzus>
    </kurzusok>

</BD_kurzusfelvetel>
