=== bakos8/M95ETT_XMLGyak/M95ETT_0928/M95ETT_orarend.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT M95ETT_orarend (ora)*>

<!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
<!ATTLIST ora 
    id CDATA #REQUIRED
    tipus CDATA #REQUIRED>
    <!ELEMENT targy (#PCDATA)>
    <!ELEMENT idopont (nap, tol, ig)>
        <!ELEMENT nap (#PCDATA)>
        <!ELEMENT tol (#PCDATA)>
        <!ELEMENT ig (#PCDATA)>
    <!ELEMENT helyszin (#PCDATA)>
    <!ELEMENT oktato (#PCDATA)>
    <!ELEMENT szak (#PCDATA)>

=== bakos8/M95ETT_XMLGyak/M95ETT_0928/M95ETT_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE M95ETT_orarend SYSTEM "./M95ETT_orarend.dtd">

<M95ETT_orarend>
    <ora id="01" tipus="eloadas">
        <targy>Adatkezeles XML kornyezetbe</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>XXXII. eloado</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>GE-BP</szak>
    </ora>

    <ora id="02" tipus="gyakorlat">
        <targy>Adatkezeles XML kornyezetbe</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf. 101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>GE-BP</szak>
    </ora>

     <ora id="03" tipus="eloadas">
        <targy>Vallalati informacios rendszerek fejlesztese</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>Inf. 103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>GE-BP</szak>
    </ora>

    <ora id="04" tipus="gyakorlat">
        <targy>Vallalati informacios rendszerek fejlesztese</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>18:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>Inf. 103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>GE-BP</szak>
    </ora>
</M95ETT_orarend>
